export const events = [
    {
      id: 1,
      name: "Live Music Concert",
      date: "2024-03-15",
      time: "8:00 PM",
      venue: "City Hall",
      availableTickets: 100,
      description: "A night of amazing music performances.",
    },
    {
      id: 2,
      name: "Comedy Show",
      date: "2024-03-22",
      time: "7:30 PM",
      venue: "Comedy Club",
      availableTickets: 50,
      description: "Laugh your heart out with top comedians.",
    },
    {
      id: 3,
      name: "Art Exhibition",
      date: "2024-04-15",
      time: "10:00 AM",
      venue: "Art Gallery",
      availableTickets: 20,
      description: "A diverse range of art pieces on display.",
    },
    {
      id: 4,
      name: "Tech Conference",
      date: "2024-05-10",
      time: "9:00 AM",
      venue: "Conference Center",
      availableTickets: 150,
      description: "Discussions with leading tech innovators.",
    },
    {
      id: 5,
      name: "Movie Premiere",
      date: "2024-05-20",
      time: "6:30 PM",
      venue: "Grand Cinema",
      availableTickets: 30,
      description: "Be the first to watch the latest blockbuster.",
    },
    {
      id: 6,
      name: "Cooking Workshop",
      date: "2024-06-05",
      time: "4:00 PM",
      venue: "Community Center",
      availableTickets: 25,
      description: "Learn to cook gourmet dishes from a top chef.",
    },
    {
      id: 7,
      name: "Football Match",
      date: "2024-06-15",
      time: "3:00 PM",
      venue: "National Stadium",
      availableTickets: 500,
      description: "Watch your favorite teams battle it out.",
    },
    {
      id: 8,
      name: "Food Festival",
      date: "2024-07-01",
      time: "11:00 AM",
      venue: "City Park",
      availableTickets: 200,
      description: "Explore a variety of cuisines and dishes.",
    },
    {
      id: 9,
      name: "Dance Performance",
      date: "2024-07-20",
      time: "7:00 PM",
      venue: "Performing Arts Center",
      availableTickets: 80,
      description: "A mesmerizing evening of dance and expression.",
    },
    {
      id: 10,
      name: "Photography Workshop",
      date: "2024-08-05",
      time: "10:00 AM",
      venue: "Studio 101",
      availableTickets: 15,
      description: "Improve your photography skills with hands-on training.",
    },
    {
      id: 11,
      name: "Marathon",
      date: "2024-08-20",
      time: "6:00 AM",
      venue: "City Streets",
      availableTickets: 1000,
      description: "Join runners from all over the city in this fun event.",
    },
    {
      id: 12,
      name: "Book Launch",
      date: "2024-09-10",
      time: "5:00 PM",
      venue: "Central Library",
      availableTickets: 40,
      description: "Meet the author and get signed copies of their latest book.",
    },
    {
      id: 13,
      name: "Jazz Night",
      date: "2024-09-25",
      time: "8:00 PM",
      venue: "Blue Note Club",
      availableTickets: 60,
      description: "Enjoy a relaxing evening with live jazz music.",
    },
    {
      id: 14,
      name: "Theater Play",
      date: "2024-10-05",
      time: "7:30 PM",
      venue: "Drama House",
      availableTickets: 100,
      description: "An enthralling play by the city's leading drama troupe.",
    },
    {
      id: 15,
      name: "Yoga Retreat",
      date: "2024-10-20",
      time: "8:00 AM",
      venue: "Green Valley",
      availableTickets: 30,
      description: "A day to relax and rejuvenate with yoga in nature.",
    },
    {
      id: 16,
      name: "Stand-up Comedy Special",
      date: "2024-11-05",
      time: "9:00 PM",
      venue: "Laugh Lounge",
      availableTickets: 70,
      description: "A hilarious evening with a renowned stand-up comedian.",
    },
    {
      id: 17,
      name: "Science Fair",
      date: "2024-11-15",
      time: "9:00 AM",
      venue: "Expo Center",
      availableTickets: 200,
      description: "Experience innovative projects and science exhibits.",
    },
    {
      id: 18,
      name: "Christmas Carnival",
      date: "2024-12-24",
      time: "5:00 PM",
      venue: "Town Square",
      availableTickets: 300,
      description: "Celebrate the holiday spirit with fun activities for all ages.",
    },
    {
      id: 19,
      name: "New Year's Eve Party",
      date: "2024-12-31",
      time: "10:00 PM",
      venue: "Skyline Club",
      availableTickets: 100,
      description: "Ring in the new year with music, drinks, and celebrations.",
    },
    {
      id: 20,
      name: "Charity Gala",
      date: "2025-01-15",
      time: "7:00 PM",
      venue: "Grand Ballroom",
      availableTickets: 50,
      description: "An evening of dining and fundraising for a noble cause.",
    },
  ];
  